apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "simplenodeservice-team03-staging"
  title: "simplenodeservice-team03-staging"
  description: "Template for the simplenodeservice owned and operated by team03 in environment staging"
  annotations:
    backstage.io/techdocs-ref: dir:.
    # Not working
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=userinterface'
    'backstage.io/kubernetes-namespace': 'simplenodeservice-team03-staging'
    argocd/app-name: simplenodeservice-team03-staging
  links:
    - url: https://github.com/ninifi/enablement-openpipeline-segments-iam.git
      title: Github Repo
      icon: github
    - url: https://stunning-space-giggle-6jqr95gr4w36g7-80.app.github.dev/simplenodeservice-team03-staging
      title: "Browse Application"
      icon: subject
    - title: View in ArgoCD
      icon: catalog
      url: https://stunning-space-giggle-6jqr95gr4w36g7-30100.app.github.dev/applications/argocd/simplenodeservice-team03-staging
    - title: View in Dynatrace
      icon: catalog
      url: https://sej59839.apps.dynatrace.com
    - url: https://community.dynatrace.com
      title: Dynatrace community
      icon: dashboard
spec:
  type: website
  owner: team03
  lifecycle: staging
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "team03"
  description: Group for application team team03
spec:
  type: business-unit
  profile:
    displayName: Team 03
    email: team03@dynatrace.training	
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  parent: applications
  children: []
#   members: [jdoe]
